# Generated by Django 2.0.13 on 2021-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
