# Generated by Django 2.0.13 on 2021-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_bond_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='debt_eq',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bond',
            name='long_debt_eq',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bond',
            name='price',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bond',
            name='roa',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bond',
            name='roe',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
