# Generated by Django 2.0.13 on 2021-03-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_auto_20210329_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='price',
            field=models.TextField(default='none'),
        ),
    ]
