# Generated by Django 2.0.13 on 2021-04-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_auto_20210331_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.TextField()),
                ('roe', models.TextField()),
                ('roa', models.TextField()),
                ('debt_eq', models.TextField()),
                ('long_debt_eq', models.TextField()),
                ('price', models.TextField(default='none')),
            ],
        ),
    ]
