# Generated by Django 2.0.13 on 2021-04-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0005_bondother'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='estimated_rate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bondother',
            name='estimated_rate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
