# Generated by Django 2.0.13 on 2021-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0006_auto_20210404_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='minprice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bond',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bondother',
            name='bid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bondother',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bondother',
            name='price',
            field=models.TextField(),
        ),
    ]
